### PR TITLE
fix: add license and generated code headers to generated resource files

### LINKED ISSUE #643: Ensure all generated files are labeled as generated in the comments
Namely, the PHP config files generated in the `resources/` directory, but we should try to add some identifying comment for all generated files.

Unfortunately, JSON does not support comments, so those are the exception.

### PR DESCRIPTION
**Pull request by Hectorhammett**
Change the `ResourcesGenerator` class to make use of the `AST::file()` method to add the required comments. I also added some comments for discussion on this PR to add them in a different PR if we come with a more elegant solution.

Fixes #643

### CODE REVIEW

File: src/Generation/ResourcesGenerator.php [hunk 1]
```diff
@@ -172,15 +172,21 @@ public static function generateDescriptorConfig(ServiceDetails $serviceDetails,
...
         );
 
-        return "<?php\n\n{$return->toCode()};";
+        $currentYear = (int)date("Y");
+
+        return AST::file(null)
+            ->withApacheLicense($currentYear)
+            ->withGeneratedCodeWarning()
+            ->withBlock($codeBlock)
+            ->toCode() . ";";
```
Comment (Hectorhammett) [inline src/Generation/ResourcesGenerator.php:189]: I am adding the `;` manually here but I am not particularly fond of this. 

My first attempt was to add this to the `return` method on `AST` but that function is used in different places. I am using the `PhpFile` class which has the ability to use a codeblock but any `PhpBlock` class implements the `ShouldNotApplySemicolonInterface` which the `AST::toPhp` method checks to decided wether or not add a semicolon.

We could create a `EndPhpBlock` or `FinalPhpBlock` class that does not implements the interface perhaps?
```php
AST::file(null)
    ->withBlock(new EndPhpBlock($string))
```

 Add an optional parameter to force the semicolon?:
```php
AST::file(null)
    ->withBlock(new PhpBlock($string))
    ->withSemiColon()
```

perhaps a method on the `PhpClass` to "finalize" the class? But perhaps the word for "Final" might be confused by a Final class. Ready perhaps? that adds a `;` to the end?
```php
AST::file(null)
    ->withBlock(new PhpBlock())
    ->ready()
```

File: src/Generation/ResourcesGenerator.php [hunk 2]
```diff
@@ -276,10 +282,17 @@ public static function generateRestConfig(ServiceDetails $serviceDetails, Servic
...
         );
-        return "<?php\n\n{$return->toCode()};";
+
+        $currentYear = (int)date("Y");
+        
+        return AST::file(null)
+            ->withApacheLicense($currentYear)
+            ->withGeneratedCodeWarning()
+            ->withBlock($codeBlock)
+            ->toCode() . ';';
```
Comment (Hectorhammett) [inline src/Generation/ResourcesGenerator.php:295]: Check above comment ☝️

File: src/Generation/ResourcesGenerator.php (hunk 1 above)
Comment (noahdietz) [reply src/Generation/ResourcesGenerator.php:189]: Interesting...I don't want to mess with `PhpBlock` too much, especially if it is already opinionated about semicolons. Given how choosy the `AST` is about semicolons altogether, I think this might be a reasonable solution to keep it how it is...or do what you suggested with a new `EndPhpBlock`...maybe `LastPhpBlock`? It just wraps a `Block` and tacks on the `;` in `toCode`?

Comment (Hectorhammett) [reply src/Generation/ResourcesGenerator.php:189]: I poked around a bit more today to see if adding the extra PHP class would help but after debugging and poking further turns out that in this case, it is actually not using the `phpBlock` class, but just a regular `AST` class and the `toPhp` method just calls `toCode` on an AST instance:
```php
elseif ($x instanceof AST) {
    return $x->toCode();
}
```

So the semicolon interface does nothing in this case lol. I think it would be best to have a way to add a semicolon codewise but for now let's keep it like it is.

Comment (noahdietz) [reply src/Generation/ResourcesGenerator.php:189]: > So the semicolon interface does nothing in this case lol. I think it would be best to have a way to add a semicolon codewise but for now let's keep it like it is.

Nice code spelunking! I agree, simple enough for now. Maybe file a `priority: p3` `type: cleanup` bug to look at this?

**Review by noahdietz — COMMENTED** [review]
You will also need to update the Bazel integration test Golden files. Those can be updated locally via the instructions in [DEVELOPMENT.md](https://github.com/googleapis/release-please/blob/main/README.md)

**Comment by noahdietz** [comment]
When updating the integration test golden files you will need to rotate the bazel cache key in the secrets. It isn't really a "secret" just where this value is stored, which indicates we want a full rebuild of the bazel workspace.

`uuidgen | gh secret set CACHE_VERSION -r https://github.com/googleapis/gapic-generator-php`

This is documented here: https://github.com/googleapis/gapic-generator-php/blob/main/DEVELOPMENT.md#rotating-the-bazel-cache-key. You may or may not have perms for this, lmk if you don't.

I've rotated and rerun the build for you.

File: MODULE.bazel.lock
Comment (noahdietz) [inline MODULE.bazel.lock:1]: Please remove this file

File: MODULE.bazel
Comment (noahdietz) [inline MODULE.bazel:1]: Please remove this file.

**Review by noahdietz — COMMENTED** [review]
Please remove the MODULE bazel files - these are created by buildifier or something when you open a WORKSPACE or BUILD.bazel file. We don't support bzlmod yet.

Maybe we should add these to the .gitignore....

**Comment by Hectorhammett** [comment]
> Please remove the MODULE bazel files - these are created by buildifier or something when you open a WORKSPACE or BUILD.bazel file. We don't support bzlmod yet.
> 
> Maybe we should add these to the .gitignore....

I removed these. Is there a reason why NOT to add them to the .gitignore? If not I could just add them rn unless there is a specific reason not to.

**Comment by noahdietz** [comment]
> I removed these. Is there a reason why NOT to add them to the .gitignore? If not I could just add them rn unless there is a specific reason not to.

Not really, unless we worry about folks forgetting that we are ignoring them if we eventually add bzlmod support haha.

Let's just add it! This PR or another is fine.

**Comment by Hectorhammett** [comment]
> > I removed these. Is there a reason why NOT to add them to the .gitignore? If not I could just add them rn unless there is a specific reason not to.
> 
> Not really, unless we worry about folks forgetting that we are ignoring them if we eventually add bzlmod support haha.
> 
> Let's just add it! This PR or another is fine.

@noahdietz 
Let's do it in a different PR. This is getting too mangled for what it is. Just a small code change and 114 files change feels like when you have a play dough getting mixed with different colours and ends up gray 🤣

**Review by noahdietz — APPROVED** [review]
